name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  docker-build:
    runs-on: macos-15
    steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         
       - name: Install Docker
         run: |
          brew install docker colima

       - name: Start Colima
         run: |
           colima start 
          

       - name: Build Docker Image
         run: |
            docker build -t tanushr/test .
  
       - name: Push Docker Image to Registry
         run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push tanushr/test
         env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
